/* testServicetestServiceService.cpp
   Generated by gSOAP 2.8.8 from WsServ/test_service.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "testService.h"

namespace testService {

testServiceService::testServiceService()
{	testServiceService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

testServiceService::testServiceService(const struct soap &_soap) : soap(_soap)
{ }

testServiceService::testServiceService(soap_mode iomode)
{	testServiceService_init(iomode, iomode);
}

testServiceService::testServiceService(soap_mode imode, soap_mode omode)
{	testServiceService_init(imode, omode);
}

testServiceService::~testServiceService()
{ }

void testServiceService::testServiceService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"test", "urn:testService", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
};

void testServiceService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void testServiceService::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	testServiceService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
testServiceService *testServiceService::copy()
{	testServiceService *dup = SOAP_NEW_COPY(testServiceService(*(struct soap*)this));
	return dup;
}
#endif

int testServiceService::soap_close_socket()
{	return soap_closesock(this);
}

int testServiceService::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int testServiceService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int testServiceService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int testServiceService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int testServiceService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void testServiceService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void testServiceService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *testServiceService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void testServiceService::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *testServiceService::soap_header()
{	return this->header;
}

int testServiceService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				return this->error;
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET testServiceService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET testServiceService::accept()
{	return soap_accept(this);
}

int testServiceService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if (dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_test__RemoteConfig(testServiceService*);

int testServiceService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "test:RemoteConfig"))
		return serve_test__RemoteConfig(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_test__RemoteConfig(testServiceService *soap)
{	struct test__RemoteConfig soap_tmp_test__RemoteConfig;
	test__ConfigRsp rsp;
	rsp.soap_default(soap);
	soap_default_test__RemoteConfig(soap, &soap_tmp_test__RemoteConfig);
	soap->encodingStyle = NULL;
	if (!soap_get_test__RemoteConfig(soap, &soap_tmp_test__RemoteConfig, "test:RemoteConfig", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->RemoteConfig(soap_tmp_test__RemoteConfig.req, rsp);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	rsp.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || rsp.soap_put(soap, "test:ConfigRsp", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || rsp.soap_put(soap, "test:ConfigRsp", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

} // namespace testService

/* End of server object code */
